--[[ // Market Shops

	-- // Fruit
	["strawberry"] 				 	 	 = {["name"] = "strawberry",							["label"] = "Strawberry",				["weight"] = 100,		["type"] = "item",		["image"] = "images/strawberry.png",					["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["apples"] 				 	 	     = {["name"] = "apples",								["label"] = "Apples",					["weight"] = 100,		["type"] = "item",		["image"] = "images/apples.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["pickle"] 							 = {["name"] = "pickle",  	     						["label"] = "Pickle",	 		 		["weight"] = 200, 		["type"] = "item", 		["image"] = "images/pickle.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "Food Ingredients" },
	["pineapple"] 					 	 = {["name"] = "pineapple",								["label"] = "Pineapple",				["weight"] = 1000,		["type"] = "item",		["image"] = "images/pineapple.png",					["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["orange"] 				 			 = {["name"] = "orange",  	     						["label"] = "Orange",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/orange.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "An Orange." },
	["blueberry"] 						 = {["name"] = "blueberry",  			    			["label"] = "Blueberry",		 		["weight"] = 100, 		["type"] = "item", 		["image"] = "images/blueberry.png", 					["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["boba"] 							 = {["name"] = "boba",  			     				["label"] = "Boba",	 					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/boba.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["lime"] 				 			 = {["name"] = "lime",  	     						["label"] = "Lime",	 					["weight"] = 200, 		["type"] = "item", 		["image"] = "images/lime.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "A Lime." },

	-- // Vegtables
	["tomato"] 				 	 	     = {["name"] = "tomato",								["label"] = "Tomatos",					["weight"] = 100,		["type"] = "item",		["image"] = "images/tomato.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["pumpkin"] 				 	 	 = {["name"] = "pumpkin",								["label"] = "Pumpkin",					["weight"] = 100,		["type"] = "item",		["image"] = "images/pumpkin.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["potato"] 							 = {["name"] = "potato",								["label"] = "Potatoes",					["weight"] = 1000,		["type"] = "item",		["image"] = "images/potato.png",						["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients" },
	["lettuce"] 	 			 		 = {["name"] = "lettuce",       						["label"] = "Lettuce",	 				["weight"] = 100, 		["type"] = "item", 		["image"] = "images/lettuce.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["onion"] 				 	 	 	 = {["name"] = "onion",									["label"] = "Onion",					["weight"] = 1000,		["type"] = "item",		["image"] = "images/onion.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["olives"] 						  	 = {["name"] = "olives",  	   			  				["label"] = "Olives",					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/olives.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "", },	
	["pizzmushrooms"] 					 = {["name"] = "pizzmushrooms",  	     				["label"] = "Mushrooms",				["weight"] = 100, 		["type"] = "item", 		["image"] = "images/mushrooms.png", 					["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "", },

	-- // Meat
	["peperoni"] 				 	 	 = {["name"] = "peperoni",								["label"] = "Peperoni Stick",			["weight"] = 1000,		["type"] = "item",		["image"] = "images/peperoni.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["tofu"] 							 = {["name"] = "tofu",  			    	 			["label"] = "Tofu",		 				["weight"] = 100, 		["type"] = "item", 		["image"] = "images/tofu.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "Food Ingredients" },
	["fish"] 							 = {["name"] = "fish",  	     						["label"] = "CatFish",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/catfish.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "A Catfish", ['hunger'] = math.random(40, 50) },
	["salami"] 							 = {["name"] = "salami",  	    						["label"] = "Salami",					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/salami.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Food Ingredients", },
	["ham"] 							 = {["name"] = "ham",  	     							["label"] = "Ham",						["weight"] = 100, 		["type"] = "item", 		["image"] = "images/ham.png", 							["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Food Ingredients", },
	["squid"] 							 = {["name"] = "squid",  	   			  				["label"] = "Calamari",					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/squid.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Food Ingredients", },	
	["frozennugget"] 				 	 = {["name"] = "frozennugget",							["label"] = "Frozen Nuggets",			["weight"] = 500,		["type"] = "item",		["image"] = "images/frozennuggets.png",					["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients"},
	["packagedchicken"] 				 = {["name"] = "packagedchicken",						["label"] = "packagedchicken",			["weight"] = 500,		["type"] = "item",		["image"] = "images/packagedchicken.png",				["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients"},
	["wholeham"] 				 		 = {["name"] = "wholeham",								["label"] = "Whole Ham",				["weight"] = 500,		["type"] = "item",		["image"] = "images/ham.png",							["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients"},
	["beef"] 				 		 	 = {["name"] = "beef",									["label"] = "Beef",					 	["weight"] = 500,		["type"] = "item",		["image"] = "images/meat.png",							["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients"},

	-- // Dairy
	["cheddar"] 						 = {["name"] = "cheddar",								["label"] = "Cheddar Slice",			["weight"] = 1000,		["type"] = "item",		["image"] = "images/cheddar.png",						["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Food Ingredients" },
	["milk"] 				 	 	 	 = {["name"] = "milk",									["label"] = "Milk",						["weight"] = 1000,		["type"] = "item",		["image"] = "images/milk.png",							["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["mozz"] 							 = {["name"] = "mozz",  	    						["label"] = "Mozzeralla",	 			["weight"] = 100, 		["type"] = "item", 		["image"] = "images/mozz.png", 							["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Food Ingredients", },
	["icecream"] 					 	 = {["name"] = "icecream",								["label"] = "Ice Cream",				["weight"] = 500,		["type"] = "item",		["image"] = "images/icecream.png",					 	["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Ice Cream."},

	-- // Leavening
	["flour"]					 		 = {["name"] = "flour", 			  					["label"] = "Flour", 					["weight"] = 1000, 		["type"] = "item", 		["image"] = "images/grain.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["yeast"] 						 	 = {["name"] = "yeast",									["label"] = "Some Yeast",				["weight"] = 1000,		["type"] = "item",		["image"] = "images/grain.png",							["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["mint"] 							 = {["name"] = "mint",  			    	 			["label"] = "Matcha",		 			["weight"] = 100, 		["type"] = "item", 		["image"] = "images/matcha.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["sugar"] 							 = {["name"] = "sugar",  			     				["label"] = "Sugar",	 				["weight"] = 100, 		["type"] = "item", 		["image"] = "images/sugar.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["nori"] 							 = {["name"] = "nori",  			    	 			["label"] = "Nori",		 				["weight"] = 100, 		["type"] = "item", 		["image"] = "images/nori.png", 							["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["basil"] 							 = {["name"] = "basil",  	   			  				["label"] = "Basil",					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/basil.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "", },
	["sauce"] 							 = {["name"] = "sauce",  	   			  				["label"] = "Tomato Sauce",	 			["weight"] = 100, 		["type"] = "item", 		["image"] = "images/sauce.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "", },

	-- // Market
	["coffeebean"] 				 	 	 = {["name"] = "coffeebean",							["label"] = "Coffee Bean",				["weight"] = 1000,		["type"] = "item",		["image"] = "images/coffeebean.png",					["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["eggs"] 				 	 	 	 = {["name"] = "eggs",									["label"] = "Eggs",						["weight"] = 100,		["type"] = "item",		["image"] = "images/eggs1.png",							["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["cream"] 				 	 	 	 = {["name"] = "cream",									["label"] = "Cream",					["weight"] = 100,		["type"] = "item",		["image"] = "images/cream.png",							["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["rice"] 				 	 	 	 = {["name"] = "rice",									["label"] = "Rice",						["weight"] = 100,		["type"] = "item",		["image"] = "images/rice.png",									["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["ketchup"] 				 	 	 = {["name"] = "ketchup",								["label"] = "Ketchup",					["weight"] = 100,		["type"] = "item",		["image"] = "images/ketchup.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["granola"] 				 	 	 = {["name"] = "granola",								["label"] = "Granola",					["weight"] = 100,		["type"] = "item",		["image"] = "images/granola.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["flavouring"] 				 	 	 = {["name"] = "flavouring",							["label"] = "Flavouring",				["weight"] = 100,		["type"] = "item",		["image"] = "images/flavour.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["rose_oil"] 				 	 	 = {["name"] = "rose_oil",								["label"] = "Rose Oil",					["weight"] = 100,		["type"] = "item",		["image"] = "images/roseoil.png",						["unique"] = false,		["useable"] = true,		["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Food Ingredients"},
	["noodles"] 						 = {["name"] = "noodles",  	     						["label"] = "Instant Noodles",	 		["weight"] = 100, 		["type"] = "item", 		["image"] = "images/noodles.png",			 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "" },
	["nachos"] 							 = {["name"] = "nachos",  	     						["label"] = "Nachos",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/nacho.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bag of Nachos", ['hunger'] = math.random(40, 50) },
	["pasta"] 							 = {["name"] = "pasta",  	     						["label"] = "Bag of Pasta",	 			["weight"] = 200, 		["type"] = "item", 		["image"] = "images/pasta.png", 						["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "A bag of Pasta", ['hunger'] = math.random(40, 50) },
	["crisps"] 							 = {["name"] = "crisps",  	    						["label"] = "Crisps",					["weight"] = 100, 		["type"] = "item", 		["image"] = "images/chips.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "", ['hunger'] = math.random(20, 30) },
	["chocolate"] 				 		 = {["name"] = "chocolate",  		     				["label"] = "Chocolate",	 			["weight"] = 200, 		["type"] = "item", 		["image"] = "images/chocolate.png", 					["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "Chocolate Bar", ['hunger'] = math.random(20, 30) },
	["cranberry"] 				 		 = {["name"] = "cranberry",  	     					["label"] = "Cranberry Juice",	 		["weight"] = 200, 		["type"] = "item", 		["image"] = "images/cranberry.png", 					["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "Cranberry Juice", ['thirst'] = math.random(20, 30) },
	["schnapps"] 				 		 = {["name"] = "schnapps",  	     					["label"] = "Peach Schnapps",	 		["weight"] = 200, 		["type"] = "item", 		["image"] = "images/schnapps.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Peach Schnapps", ['thirst'] = math.random(20, 30) },
	["gin"] 					 		 = {["name"] = "gin",  	     							["label"] = "Gin",	 					["weight"] = 200, 		["type"] = "item", 		["image"] = "images/gin.png", 							["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Gin", ['thirst'] = math.random(20, 30) },
	["scotch"] 					 		 = {["name"] = "scotch",  	     						["label"] = "Scotch",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/rum.png", 							["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Scotch", ['thirst'] = math.random(20, 30) },
	["rum"] 					 		 = {["name"] = "rum",  	     							["label"] = "Rum",	 					["weight"] = 200, 		["type"] = "item", 		["image"] = "images/rum.png", 							["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Rum", ['thirst'] = math.random(20, 30) },
	["icream"] 					 		 = {["name"] = "icream",  	     						["label"] = "Irish Cream",	 			["weight"] = 200, 		["type"] = "item", 		["image"] = "images/Irishcream.png", 				    ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Irish Cream Liquer", ['thirst'] = math.random(20, 30) },
	["amaretto"] 						 = {["name"] = "amaretto",  	     					["label"] = "Amaretto",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/amaretto.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Amaretto", ['thirst'] = math.random(20, 30) },
	["curaco"] 							 = {["name"] = "curaco",  	     						["label"] = "Curaco",	 				["weight"] = 200, 		["type"] = "item", 		["image"] = "images/curaco.png", 						["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,   	["combinable"] = nil,   ["description"] = "A bottle of Curaco", ['thirst'] = math.random(20, 30) },
	["pizzadough"] 						 = {["name"] = "pizzadough",  	    					["label"] = "Pizza Dough",	 			["weight"] = 100, 		["type"] = "item", 		["image"] = "images/pizzadough.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false,   	["combinable"] = nil,   ["description"] = "", },

	["slicedpotato"] 				= {["name"] = "slicedpotato",				["label"] = "Sliced Potatoes",			["weight"] = 500,		["type"] = "item",		["image"] = "images/slicedpotato.png",	["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Sliced Potato"},
	["slicedonion"] 				= {["name"] = "slicedonion",				["label"] = "Sliced Onions",			["weight"] = 500,		["type"] = "item",		["image"] = "images/slicedonion.png",	["unique"] = false, 	["useable"] = false,	["shouldClose"] = false,	["combinable"] = nil,	["description"] = "Sliced Onion"},
]]--